config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'

  resources :recipes, only: %i[new create show index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_reader :title, :recipe_type_id, :cuisine_id, :difficulty,
              :cook_time, :ingredients, :cook_method, :user_id,
              :status

  def initialize(title: nil, recipe_type_id: nil, cuisine_id: nil,
                 difficulty: nil, cook_time: nil, ingredients: nil,
                 cook_method: nil, user_id: nil, status: nil,
                 created_at: nil, updated_at: nil, id: nil)
    @title = title
    @recipe_type_id = recipe_type_id
    @cuisine_id = cuisine_id
    @difficulty = difficulty
    @cook_time = cook_time
    @ingredients = ingredients
    @cook_method = cook_method
    @user_id = user_id
  end

  def persisted?
    false
  end

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id,
                                   :difficulty, :cook_time, :ingredients,
                                   :cook_method, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'net/http'
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
    
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    url = 'http://localhost:3000/api/v1/recipes'
    resp = Faraday.get(url)
    recipes = JSON.parse(resp.body)
    @recipes = recipes.map { |recipe| Recipe.new(recipe.symbolize_keys) }
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params[:recipe].as_json)

    url = 'http://localhost:3000/api/v1/recipes'

    resp = Faraday.post(url) do |req|
      req.headers['Content-Type'] = 'application/json'
      req.body = { recipe: @recipe.instance_values }.to_json
    end

    if resp.status == 201
      @recipe = JSON.parse(resp.body)
      redirect_to recipe_path(@recipe['id'])
    else
      flash[:warning] = resp.body
      render :new
    end

  end

  def show
    url = "http://localhost:3000/api/v1/recipes/#{params[:id]}"

    resp = Faraday.get(url)
    @recipe = JSON.parse(resp.body)
  end

  def recipe_params
    params.permit(:title, :recipe_type_id, :cuisine_id,
                  :difficulty, :cook_time, :ingredients,
                  :cook_method, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookbookIntegration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home', root_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/main.html.erb
<h1>This project integrates the cookbook-treinadev project</h1>

<p><%= link_to 'Cadastrar receita', new_recipe_path %></p>

<p><%= link_to 'Listar receitas', recipes_path %></p>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
  <div class='row'>
    <div class='col-3'>
      <p><%= link_to recipe.title, recipe, class: 'link' %></p>
      <p><%= "type: #{recipe.recipe_type_id}" %></p>
      <p><%= "cuisine: #{recipe.cuisine_id}" %></p>
      <p><%= "difficulty: #{recipe.difficulty}" %></p>
      <p><%= "cook_time: #{recipe.cook_time}" %></p>
      <p><%= "ingredients: #{recipe.ingredients}" %></p>
      <p><%= "cook_method: #{recipe.cook_method}" %></p>
      <p><%= "user_id: #{recipe.difficulty}" %></p>
    </div>
  </div>
  <br>
<% end %>

app/views/recipes/new.html.erb
<h1>Creates new recipe</h1>

<%= @example %>

<%= form_for @recipe do |f| %>
  <table>
    <tr>
      <td><%= f.label :title, (t 'title') %></td>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <td><%= f.label :recipe_type_id, (t 'recipe_type') %></td>
      <td><%= f.number_field :recipe_type_id %></td>
    </tr>
    <tr>
      <td><%= f.label :cuisine_id, (t 'cuisine') %></td>
      <td><%= f.number_field :cuisine_id %></td>
    </tr>
    <tr>
      <td><%= f.label :difficulty, (t 'difficulty') %></td>
      <td><%= f.text_field :difficulty %></td>
    </tr>
    <tr>
      <td><%= f.label :cook_time, (t 'cook_time') %></td>
      <td><%= f.number_field :cook_time %></td>
    </tr>
    <tr>
      <td><%= f.label :ingredients, (t 'ingredients') %></td>
      <td><%= f.text_area :ingredients %></td>
    </tr>
    <tr>
      <td><%= f.label :cook_method, (t 'cook_method') %></td>
      <td><%= f.text_area :cook_method %></td>
    </tr>
    <tr>
      <td><%= f.label :user_id, (t 'user_id') %></td>
      <td><%= f.number_field :user_id %></td>
    </tr>
    <tr>
      <td><%= f.submit ('submit') %></td>
    </tr>
  </table>
<% end %>

<%= link_to (t 'back'), root_path %>

app/views/recipes/show.html.erb
<div class='row'>
  <div class='col'>
    <h1><%= @recipe['title'] %></h1>

    <p><%= "Submitted by user_id: #{@recipe['user_id']}" %></p>

    <h3><%= 'details' %></h3>
    <table>
      <tr>
        <td><%= 'type_id' %>:</td>
        <td><%= @recipe['recipe_type_id'] %></td>
      </tr>
      <tr>
        <td><%= 'cuisine_id' %>:</td>
        <td><%= @recipe['cuisine_id'] %></td>
      </tr>
      <tr>
        <td><%= 'cook_time' %>:</td>
        <td><%= @recipe['cook_time'] %></td>
      </tr>
      <tr>
        <td><%= 'difficulty' %>:</td>
        <td><%= @recipe['difficulty'] %></td>
      </tr>
    </table>
  </div>
</div>

<div class='row'>
  <div class='col'>
    <table>
      <tr>
        <td><%= 'ingredients' %>:</td>
        <td><%= @recipe['ingredients'] %></td>
      </tr>
    </table>
  </div>

  <div class='col'>
    <table>
      <tr>
        <td><%= 'cook_method' %>:</td>
        <td><%= @recipe['cook_method'] %></td>
      </tr>
    </table>
  </div>
</div>
<%= link_to 'back', root_path %>